services:
  - type: web
    name: chatbot-nsi
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
